apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true

  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    access: proxy
    url: timescaledb:5432
    user: procwatcher
    editable: true
    secureJsonData:
      password: procwatcherpw
    jsonData:
      database: procwatcherdb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
